:sparkles: add full support of any type of graphql resolver
cuillerejs/cuillere pull request #43
Opened 2020-10-15 14:05 UTC by Taranys

Hi,

A add this PR to support all type of resolvers. Right now, array of resolvers or scalar are not working.

I took some time to enable TS types everywhere to be sure that you will be warn after an upgrade if appolo add a new type of resolver.

2020-10-15 15:15 UTC, nlepage requested changes
Some suggestions

2020-10-15 15:15 UTC, nlepage commented on graphql/package.json
> +    "graphql": "~14"
```suggestion
    "apollo-server-koa": "^2.15.1"
  },
  "dependencies": {
    "graphql": "~14"
  },
```

2020-10-15 15:15 UTC, nlepage commented on graphql/src/index.ts
> +    return Object.entries(resolvers).reduce((resolver: IResolvers, [key, value]) => {
I'd rather have a for loop assigning to a const object.

2020-10-15 15:15 UTC, nlepage commented on graphql/src/index.ts
> +  return resolverObject => Object.entries(resolverObject).reduce((resolver: IResolverObject, [key, value]) => {
Same here

2020-10-16 15:00 UTC, EmrysMyrddin approved these changes

2020-10-16 19:09 UTC, nlepage approved these changes

2020-10-16 19:13 UTC, merged