:sparkles: handle executable schema option
cuillerejs/cuillere pull request #52
Opened 2021-01-06 17:08 UTC by EmrysMyrddin

2021-01-07 09:10 UTC, nlepage approved these changes

2021-01-07 09:10 UTC, nlepage commented on yarn.lock
> +graphql-tag@^2.11.0, graphql-tag@^2.9.2:
Hum ce serait bien si on utilisait la même version

2021-01-08 10:04 UTC, nlepage requested changes
Nice one

2021-01-08 10:04 UTC, nlepage commented on server/src/server.ts
> +    }
```suggestion
    if (!isCuillereExecutableSchema(apolloConfig.schema)) throw new Error('To make an executable schema, please use `makeExecutableSchema` from `@cuillere/server`.')
```

2021-01-08 10:04 UTC, nlepage commented on server/src/server.ts
> +export function getResolvers({ plugins, contextKey }: CuillereConfig, { resolvers }: ApolloConfig) {
On pourrait déplacer le makeExecutableSchema, ça éviterait d'exporter ça

2021-01-08 13:26 UTC, EmrysMyrddin commented on yarn.lock
> +graphql-tag@^2.11.0, graphql-tag@^2.9.2:
C'est une dépendence de dev pour les tests mais oui je peux

2021-01-08 13:32 UTC, EmrysMyrddin commented on tsconfig-node12.json
>  }
```suggestion
}

```

2021-01-08 13:32 UTC, EmrysMyrddin commented on tsconfig-node14.json
>  }
```suggestion
}

```

2021-01-08 13:47 UTC, nlepage approved these changes

2021-01-08 13:55 UTC, merged